package:
  name: iminuit
  version: 2.28.0
source:
  url: https://files.pythonhosted.org/packages/d8/c3/9385361c5f115928c1490422d9d824581141f8f444096a6ed00009add74e/iminuit-2.28.0.tar.gz
  sha256: "6646ae0b66a4760e02cd73711d460a6cf2375382b78ce8344141751595596aad"
test:
  imports:
    - iminuit
requirements:
  run:
    - numpy # runtime only
build:
  script: |
    export CMAKE_ARGS="-DPYBIND11_FINDPYTHON=ON"
  cxxflags: -fexceptions
  ldflags: -fexceptions
about:
  home: http://github.com/scikit-hep/iminuit
  PyPI: https://pypi.org/project/iminuit
  summary: Jupyter-friendly Python frontend for MINUIT2 in C++
  license: MIT+LGPL
extra:
  recipe-maintainers:
    - henryiii
