package:
  name: iminuit
  version: 2.25.2
source:
  url: https://files.pythonhosted.org/packages/78/f1/416e559122a3872878853429a87143b4b4f5d33e23c1317be8a270e875aa/iminuit-2.25.2.tar.gz
  sha256: "3bf8a1b96865a60cedf29135f4feae09fa7c66237d29f68ded64e97a823a9b3e"
test:
  imports:
    - iminuit
requirements:
  run:
    - numpy # runtime only
build:
  cxxflags: -fexceptions
  ldflags: -fexceptions
about:
  home: http://github.com/scikit-hep/iminuit
  PyPI: https://pypi.org/project/iminuit
  summary: Jupyter-friendly Python frontend for MINUIT2 in C++
  license: MIT+LGPL
extra:
  recipe-maintainers:
    - henryiii
